### ISSUE TITLE
Meter provider - integration test

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#665]
Current state

* [x] ASP.NET Core metrics - #716
* [x] ASP.NET metrics - #901
* [x] HTTP client metrics - #716
* [x] .NET runtime metrics - #900 
* [x] plugins - #910
* [x] manual metrics - #898
* [x] Prometheus exporter (test app with manual metrics) https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/918

**Comment by Kielek** [comment]
Current state
* [x] ASP.NET Core metrics #716
* [ ] ASP.NET metrics #851
* [x] Http client metrics -  #716
* [ ] runtime metrics
* [ ] manual metrics

**Comment by pellared** [comment]
I will start working on it today.

**Comment by rajkumar-rangaraj** [comment]
I'm sorry @pellared, revisited the issue while creating the PR and realized you are also working on the same.
